version: '3'
services:
  app:
    image: wagena/laravel:latest
    networks:
     - appnet
    volumes:
     - ../:/var/www/html
    working_dir: /var/www/html
    ports:
     - ${APP_PORT}:80
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
     - appnet
    ports:
     -  ${DB_PORT}:3306
    volumes:
     - dbdata:/var/lib/mysql
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
